### ISSUE TITLE
[docs] 피그마로 UI 디자인하기

### ISSUE THREAD

**Issue by LEE-DA-EUN** [kakaotech-25/moheng#13]
### 🕹️ 구현할 기능

- 리액트로 구현할 화면을 피그마로 디자인하기

#### PC 화면
- [x] 1. 로그인
- [x] 2. 메인페이지-로그인전
- [x] 3. 메인페이지-로그인후
- [x] 3-1. 태그 검색 모달
- [x] 4. 마이페이지 tab1
- [x] 5. 마이페이지 tab2
- [x] 6. 최초 입력 1 - 기본 정보
- [x] 7. 최초 입력 2 - 생활 정보
- [x] 8. 최초 입력 3 - 관심 여행지
- [x] 9. 여행지 세부
- [x] 9-1. 북마크 모달
- [x] 10. 플래너
- [x] 10-1. 일정추가 모달
- [x] 10-2. 일정수정 모달
- [x] 11. 플래너 세부
-
- [x] 모바일 UI로 변경 
- [x] 1. 로그인
- [x] 2. 메인페이지-로그인전
- [x] 3. 메인페이지-로그인후
- [x] 3-1. 태그 검색 모달
- [x] 4. 마이페이지 tab1
- [x] 5. 마이페이지 tab2
- [x] 6. 최초 입력 1 - 기본 정보
- [x] 7. 최초 입력 2 - 생활 정보
- [x] 8. 최초 입력 3 - 관심 여행지
- [x] 9. 여행지 세부
- [x] 9-1. 북마크 모달
- [x] 10. 플래너
- [x] 10-1. 일정추가 모달
- [x] 10-2. 일정수정 모달
- [x] 11. 플래너 세부

### ⏰ 예상소요시간

- 3일

**Comment by msung99** [comment]
lian .... 고생이 많습니다 후덜덜 ... 🥹
