### ISSUE TITLE
[feat] API호출과 로컬 개발을 위한 도커컴포즈 작성

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#151]
### 🕹️ 구현할 기능

도커컴포즈를 통해서 컨테이너 개발환경을 구축합니다. 

### 🛠️ 상세작업내용

- [x] 1. 도커컴포즈로 백엔드 컨테이너와 프론트 컨테이너를 같이 구동하여 로컬 개발환경을 셋팅합니다.
- [x] 2. AI컨테이너 추가

### ⏰ 예상소요시간

1

**Comment by msung99** [comment]
axios 예제코드는 어떤 API 로 하나요??

**Comment by JaeJunday** [comment]
> axios 예제코드는 어떤 API 로 하나요??

회원가입으로 테스트해볼예정입니다. 다른것은 access token있어야 요청 정상적으로 처리되지 않나요?

**Comment by msung99** [comment]
회원가입 API 가 아래에서 수행되는 API 맞죠?? 여기도 엑세스 토큰이 있어야 회원가입이 가능합니다!!

![image](https://github.com/user-attachments/assets/ebee96ac-08c3-41aa-a948-9de722b1d8fe)

**Comment by JaeJunday** [comment]
@msung99 감사합니다. 저걸로 테스트 작성해보겠습니다.
