### ISSUE TITLE
[feat] 플래너 세부 페이지 UI 구현

### ISSUE THREAD

**Issue by LEE-DA-EUN** [kakaotech-25/moheng#168]
### 🕹️ 구현할 기능

플래너 페이지에서 일정을 누르면 해당 일정과 연결되는 세부 페이지 UI를 구현합니다.

### 🛠️ 상세작업내용

- [x] 1. 플래너페이지에서 일정을 누르면 해당 일정의 세부페이지를 보여주기
- [x] 2. 일정에 담긴 여행지리스트 구현
- [ ] 3. 지도api 사용해서 지도 UI 구현
- [ ] 4. 여행지별 삭제버튼과 햄버거버튼 구현
- [ ] 5. 일정 수정하기 버튼을 누르면 모달 띄워주기
- [ ] 6. 일정이름, 일정기간 수정후 save버튼누르면 수정된 내용 저장
- [ ] 7. 뒤로가기 버튼 구현

### ⏰ 예상소요시간

2일

**Comment by msung99** [comment]
지도에 표시해야 할 여행지의 좌표값은 백엔드에서 리턴하니 참고해주세요 ~

**Comment by LEE-DA-EUN** [comment]
넵!! 참고해서 구현하겠습니다~
