### ISSUE TITLE
[Bug] 소나클라우드 백엔드 프로젝트 이름 자동 변경 버그

### ISSUE THREAD

**Issue by rimeir** [kakaotech-25/moheng#191]
### 📍 문제 상황

setting.gradle 파일에 rootProject.name이 demo로 설정되어 있어 소나클라우드 백엔드 프로젝트 이름이 자동으로 moheng-backend에서 demo로 변경되었습니다.

### 🎯 해결 방법

build.gradle에 소나큐브 프로젝트 이름을 명시합니다.

### ⭐️ 중요도

하 - 당장 해결하지 않아도 되지만 잠재적 영향이 있을 수 있음

**Comment by JaeJunday** [comment]
조금 더 정확하게 어떤 상황인지 공유해주세요. 자동변경된다는게 무슨 상태인지 이해되지 않습니다.
