### ISSUE TITLE
[feat] Jenkins를 통한 CI 구축

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#20]
### 🕹️ 구현할 기능

- 풀리퀘스트가 발생했을 때 Jenkins를 통하여 빌드와 테스트를 진행합니다.
- Jenkin pipelines의 성공, 실패여부에 따라 해당코드를 수락, 거부하는 룰을 지정합니다.

### 🛠️ 상세작업내용

- [x] 1. 프로젝트에 Jenkins와 연결할 webhook 생성
- [x] 2. 깃허브 레포지토리 설정에서 브랜치 머지 룰 설정

### ⏰ 예상소요시간

4

**Comment by msung99** [comment]
컨트롤러 - 에이전트가 `Master` - `Slave ` 구조인가용?

**Comment by JaeJunday** [comment]
> 컨트롤러 - 에이전트가 `Master` - `Slave ` 구조인가용?

네 동일합니다. 단지 Master-Slave의 좋지 않은 어감 때문에 최근에 들어서 controler / agent로 순화하여 표현하는것으로 알고있습니다.
쿠버네티스도 비슷하게 control plane - agent node 로 명명하고 있기도 합니다.
