### ISSUE TITLE
[feat] ec2 데이터베이스 설치

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#263]
### 🕹️ 구현할 기능

데이터 베이스 설치패키지를 서브모듈로 구현합니다.

### 🛠️ 상세작업내용

- [x] 1. mysql 8.0 이미지와 컨테이너 설정파일
- [x] 2. 데이터베이스와 스키마가 정의된 설정파일
- [x] 3. 서브모듈에 연동

### ⏰ 예상소요시간

4

**Comment by msung99** [comment]
이거 다 끝난 이슈인가요??

**Comment by JaeJunday** [comment]
> 이거 다 끝난 이슈인가요??

네 맞습니다.
