### ISSUE TITLE
[feat] 백엔드 h2 인메모리 데이터베이스를 mysql로 이주합니다.

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#364]
### 🕹️ 구현할 기능

- 데이터베이스의 url 설정을 mysql로 변경했을 때 동작하도록 로컬에 데이터베이스 초기화를 자동화합니다.
- 프로덕션에서 최종적으로 데이터베이스는 ec2 단일 머신 클러스터링 혹은 RDS서비스를 이용합니다.

### 🛠️ 상세작업내용

- [x] 1. 서브모듈에 대한 초기화 스크립트 작성
- [x] 2. 스크립트 모음으로 정리
- [x] 3. task 명령어 정리 & 통합관리

### ⏰ 예상소요시간

3

**Comment by msung99** [comment]
wow 벌써 작업하나염 쉬엄쉬엄 하숑 ㅎㅎ

**Comment by JaeJunday** [comment]
> wow 벌써 작업하나염 쉬엄쉬엄 하숑 ㅎㅎ

아하 코드짜는것도 아닌데요. 이러면서 쉬는 겁니다.

**Comment by msung99** [comment]
이건 아직 처리중이져??
