### ISSUE TITLE
[feat] 프로메테우스와 그라파나 도입

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#422]
### 🕹️ 구현할 기능

- 서버의 시계열 매트릭을 수집하고, 보여줄 수 있는 프로메테우스와 그라파나를 도입합니다.
- 특정 임계값에 따라 알림을 보내는 정책을 수립합니다.
- 프로메테우스와 그라파나의 설정을 문서화합니다.

### 🛠️ 상세작업내용

- [x] 1. cAdvisor, node exporter를 설치합니다.
- [x] 2. 프로메테우스, 그라파나 설치 및 가동
- [x] 3. 특정 이벤트에 관리툴로 알림 전송 기능 추가

### ⏰ 예상소요시간

12

**Comment by msung99** [comment]
옛날에 Grafana, Prometheus, Spring Actuator 기반 모니터링 환경 구축 찍먹한 내용인데 참고하세요 ~~ 

https://haon.blog/haon/infra/monitoring/grafana-prometheus/
