### ISSUE TITLE
[feat] 백엔드 작업을 위한 애플리케이션 추가 환경 구축

### ISSUE THREAD

**Issue by msung99** [kakaotech-25/moheng#5]
## 🤷 구현할 기능

백엔드 작업을 위한 애플리케이션 추가 환경을 구축합니다.

## 🔨 상세 작업 내용

- [x] h2 데이터베이스 설치 및 인메모리 설정
- [x] 4-tier 모놀리식 아키텍처 구성
- [x] 예외처리를 위한 RestControllerAdvice 추가
- [x] JpaAuditConfig 설정
- [x] BaseEntity 설계
- [x] Member 엔티티 설계 및 단위 테스트

## ⏰ 예상 소요 기간

3시간

**Comment by JaeJunday** [comment]
4-tier 모놀리식 아키텍쳐 구성은 백엔드 내의 구성인가요? 아니면 전체 프로젝트와 관련있을까요?

**Comment by msung99** [comment]
@JaeJunday 백엔드 내의 아키텍처 구성입니다 👍

**Comment by msung99** [comment]
계층형 아키텍처 관련해서는 아래 포스트 참고해도 좋을듯 !!!!

https://haon.blog/spring/layered-architecture/
