### ISSUE TITLE
[feat] Jenknis의 빌드 성공 / 실패시 디스코드 알림 

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#61]
### 🕹️ 구현할 기능

- 젠킨스의 빌드가 성공 / 실패했을때 디스코드 알림을 보내 실시간으로 확인할수있도록 합니다.

### 🛠️ 상세작업내용

- [x] 1. 젠킨스에 디스코드 도구 설치 
- [x] 2. 젠킨스 파이프라인에 디스코드와 연동 코드 작성  작성 
- [x] 3. PR 테스트

### ⏰ 예상소요시간

4

**Comment by msung99** [comment]
오 이거 딱 필요하다 느꼈는데 댑악 ~~
