### ISSUE TITLE
[feat] jacoco 를 도입하여 테스트 커버리지 측정하기

### ISSUE THREAD

**Issue by msung99** [kakaotech-25/moheng#68]
### 🕹️ 구현할 기능

현재 백엔드 프로젝트 내의 명확한 테스트 품질 측정 및 커버리지 판단 기준이 없습니다. 즉, 테스트 코드의 품질과 신뢰도를 판단할 수 있는 정량적 지표가 존재하지 않습니다. 좋은 테스트라는 명확한 지표가 있어야지 더욱 믿음직한 프로덕션 코드가 도출될 것입니다.

따라서, jacoco 를 도입하여 테스트 커버리지를 측정하여 명확한 지표와 근거를 만들고자 합니다.  

테스트 커버리지가 높으면, 이전보다 더 과감하게 코드를 리팩토링할 수 있습니다. 리팩토링에 문제가 있다면 테스트 코드가 알려줄 것입니다. 
비슷한 이유로 배포도 더 자신있게 할 수 있게됩나다.  

### 🛠️ 상세작업내용

- [x] build.gradle 에 jacoco 관련 의존성 추가
- [x] SonarQube (또는 github actions 등) 도입과 관련하여 클라우드 팀과 논의 
  - 💡 SonarQube는 자체적으로 코드 커버리지를 측정하지 않으며, 외부 도구(JaCoCo 등)를 사용하여 코드 커버리지 데이터를 생성해야 합니다.)
  - 💡 JaCoCo가 생성한 코드 커버리지 보고서를 SonarQube가 분석하고 시각화할 수 있습니다.
- [x] 코드 커버리지 측정 결과 퍼센트가 일정 수준 이하면 빌드가 실패하도록 설정
  - 커버리지 최솟값은 아직 고민 중

## 참고하면 좋을 자료

- https://velog.io/@ttanggin/HowtoStartSonarQube
- https://hudi.blog/code-coverage/
- https://sungsan.oopy.io/1d6e3f0c-7a3e-48f2-bb62-ad0e37e3c888

### ⏰ 예상소요시간

3시간

**Comment by JaeJunday** [comment]
쿠버네티스 환경이 아닌곳에서 소나큐브를 도입하는 경우 직접 소나큐브 서버를 어느곳에 띄울지 고려해야합니다.
젠킨스 인스턴스에 같이 구동할지, 새로운 소나큐브 인스턴스를 가동할지 장단점을 따져보겠습니다.
