### ISSUE TITLE
[feat] pure react환경을 react-vite로 마이그레이션

### ISSUE THREAD

**Issue by JaeJunday** [kakaotech-25/moheng#90]
### 🕹️ 구현할 기능

번들링 도구로 Vite를 도입하면서 기존에 구성했던 환경(react-create-app)을 업데이트하는 작업을 진행합니다.

### 🛠️ 상세작업내용

- [x] 1. vite + react 앱 초기화
- [x] 2. 도커파일 / 컴포즈 파일 포트 바인딩 수정
- [x] 3. 로컬 테스트

### ⏰ 예상소요시간

1시간

**Comment by msung99** [comment]
1이 1시간인가요 1일인가요??

**Comment by JaeJunday** [comment]
> 1이 1시간인가요 1일인가요??

헉 앞으론 단위를 추가하도록하겠습니다.

**Comment by LEE-DA-EUN** [comment]
로컬테스트 완료했습니다! 잘 작동합니다!
