### ISSUE TITLE
[test] 프론트엔드 레이아웃 예제 코드

### ISSUE THREAD

**Issue by Do-yoon** [kakaotech-25/moheng#98]
### 🕹️ 구현할 기능

레이아웃 컴포넌트를 작성하는 예시를 제공합니다. 이 이슈는 develop 브랜치에 병합하지 않습니다. 코드 확인 후 브랜치를 삭제하셔도 좋습니다.

### 🛠️ 상세작업내용

- [x] 1. 레이아웃 컴포넌트를 작성합니다.

### ⏰ 예상소요시간

1시간

**Comment by LEE-DA-EUN** [comment]
예제 감사합니다!
